# Generated by Django 4.0.5 on 2022-07-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tipo_de_familia', models.CharField(max_length=20)),
                ('age', models.FloatField()),
            ],
        ),
    ]
